include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    invalid_annotation_target: ignore
    missing_required_param: warning
    missing_return: warning
  exclude:
    - "lib/**/*.g.dart"
    - "lib/**/*.freezed.dart"
  language:
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    always_use_package_imports: false
    prefer_relative_imports: true
    sort_constructors_first: true
