include: package:lint/strict.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    invalid_annotation_target: ignore
    missing_required_param: warning
    missing_return: warning
  exclude:
    - "test/**"
    - "build/**"
    - "windows/**"
    - "lib/**/*.g.dart"
    - "lib/**/*.freezed.dart"
  language:
    strict-inference: true
    strict-raw-types: true
  plugins:
    - custom_lint

linter:
  rules:
    always_put_required_named_parameters_first: false
    always_specify_types: false
    always_use_package_imports: false
    prefer_double_quotes: false
    prefer_relative_imports: true
    prefer_single_quotes: true
    sort_constructors_first: true
    use_key_in_widget_constructors: true
